### ISSUE TITLE
Value prop is not updating when initalized with 0

### ISSUE THREAD

**Issue by alekbless** [palerdot/vue-speedometer#22] opened 2020-11-25 15:05 UTC
Hello,

Iam having trouble setting the value to 0 after any other value. 

To reproduce locally: 
1. Intialize with a value of 0 via computed or prop from parent.
2. Set the value to 15 updating the speedometer. 
3. Set the value back to 0 and it won't update.

**NOTE** Setting the force-render to true updates the value, but only due to complete re-render.

**Comment by palerdot** [comment] 2020-11-26 12:08
@alekbless can you please share a reproducible codesandbox? 

I will take a look at this once we have a minimal reproduction.

Thanks

**Comment by palerdot** [comment] 2020-11-26 12:11
I think I got the issue. It may be because of how new value is handled [here](https://github.com/palerdot/vue-speedometer/blob/master/src/index.js#L79). In any case, let me know you have a minimal reproduction in code sandbox ...

**Comment by palerdot** [comment] 2020-11-27 13:58
This issue is fixed in `v1.8.0`. Reference sandbox - https://codesandbox.io/s/angry-diffie-qc4r1?file=/src/App.vue

Please update to latest `v1.8.0` for the fix.

**Closed by palerdot** 2020-11-27 13:58 UTC
Labels: bug, needs reproduction

**Comment by alekbless** [comment] 2020-11-30 10:18
Thanks @palerdot

The prop is now updated with the new value.
